---
deployment:
 tasks:
 - export DEPLOYPATH=/home/invartic/public_html/cards
 - /bin/cp css/*.* /home/invartic/public_html/cards/css
 #- /bin/cp data/*.* $DEPLOYPATH/data
 #- /bin/cp html/*.* $DEPLOYPATH/html
 #- /bin/cp image/*.* $DEPLOYPATH/image
 #- /bin/cp script/*.* $DEPLOYPATH/script
 #- /bin/cp template/*.* $DEPLOYPATH/template
 - /bin/cp index.html $DEPLOYPATH
 - /bin/cp config.json $DEPLOYPATH
