---
deployment:
 tasks:
 - export DEPLOYPATH=/home/invartic/public_html/cards
 - /bin/cp css/*.* $DEPLOYPATH
 - /bin/cp data/*.* $DEPLOYPATH
 - /bin/cp html/*.* $DEPLOYPATH
 - /bin/cp image/*.* $DEPLOYPATH
 - /bin/cp script/*.* $DEPLOYPATH  
 - /bin/cp template/*.* $DEPLOYPATH
 - /bin/cp index.html $DEPLOYPATH
 - /bin/cp config.json $DEPLOYPATH
